modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/3arthqu4ke/pingbypass"
license = "MIT"

[[mods]]
modId = "pingbypassserver"
version = "${version}"
displayName = "PingBypass-Server"
authors = "3arthqu4ke"
description = "The PingBypass Server"

[[dependencies.pingbypassserver]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.pingbypassserver]]
modId = "pingbypass"
mandatory = true
versionRange = "[${version}]"
ordering = "NONE"
side = "CLIENT"
