modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/3arthqu4ke/pingbypass"
license = "MIT"

[[mods]]
modId = "pingbypassclient"
version = "${version}"
displayName = "PingBypass-Client"
authors = "3arthqu4ke"
description = "The PingBypass Client"

[[dependencies.pingbypassclient]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.pingbypassclient]]
modId = "pingbypass"
mandatory = true
versionRange = "[${version}]"
ordering = "NONE"
side = "CLIENT"
