name: Build Project

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build sources jar
        run: ./gradlew sourcesJar

      - name: Build javadoc jar
        run: ./gradlew javadocJar

      - name: Build jars
        run: ./gradlew build
